data:
  raw: data/raw/ObesityDataSet_raw_and_data_sinthetic.csv
  interim: data/interim/obesity_clean.csv
  processed_dir: data/processed
  train: data/processed/train.csv
  validation: data/processed/validation.csv
  test: data/processed/test.csv

split:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  stratify: true
  target: Obesity

train:
  model_dir: models/obesity-clf
  metrics_out: metrics.json
  random_state: 42
  n_estimators: 300
  max_depth: null